### ISSUE TITLE
This repo should be the default version because ¡it works!

### ISSUE THREAD

**Issue by dgfmdrv** [KC-SAS/kairosdb-grafana-enhanced-plugin#1]
Hello, 

Grafana team archived their kairos-datasource repository today. The don't know that this version works well¡!

grafana/kairosdb-datasource#94

Thank you

**Comment by daniellee** [comment]
We would be happy to publish this plugin on grafana.com and remove the existing kairosdb plugin from the plugin catalog. We haven't been maintaining the kairosdb plugin for years and unfortunately have not found anyone willing to take it over.

If KC SAS want this to be a published plugin, then they can submit the plugin for review by following the instructions here: https://github.com/grafana/grafana-plugin-repository#community-plugins

It would be great to have a working, maintained plugin that we can point people to.

**Comment by lcoulet** [comment]
Hello, thank you.
If someone would want to publish this plugin, or create a fork based on this one - we would be happy to support it.

This plugin is an automated machine-generated code base from a plugin that supports custom extensionsto KairosDB - the plugin signature system with publishing to Grafana that will forbid to deploy custom plugins in private on-premises Grafana instances will be a blocker for us so we don't know what we are going to do yet regarding Grafana. We do not use ourselves this particular plugin and we do not spend time and effort testing it (we test the more customized extended version).

So we will not publish our plugin to Grafana for signature  anytime soon - this plugin as been made as-is and we do not want to commit to any kind of liability. 
We share it for the sake of the community and because KairosDB is a great, underrated, time series database, and Grafana is a great (and the best) time series dashboard & visualization system.

Last but not least, unfortunately we also may not for instance support Grafana 8 anytime soon (due to license changes and the announcement of not supporting unsigned plugins anymore) , which since recently makes publishing this plugin to Grafana.com useless for most people.

**Comment by daniellee** [comment]
>  which since recently makes publishing this plugin to Grafana.com useless for most people.

If the plugin is published to Grafana.com then we will sign it and it will be easy to install on any version of Grafana. Supporting Grafana 8 wouldn't affect the license of this plugin either.

Also, it is possible to run unsigned plugins - just that it has to be a conscious choice by the user to do that: https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins
